"""empty message

Revision ID: 8149ec974e7d
Revises: 
Create Date: 2022-09-24 00:38:08.815122

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8149ec974e7d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('MFD',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('common_id', sa.Integer(), nullable=False),
    sa.Column('spoolID', sa.String(length=13), nullable=False),
    sa.Column('create_date', sa.DateTime(), nullable=False),
    sa.Column('mfd1310ise', sa.REAL(), nullable=True),
    sa.Column('mfd1310ose', sa.REAL(), nullable=True),
    sa.Column('mfd1550ise', sa.REAL(), nullable=True),
    sa.Column('mfd1550ose', sa.REAL(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('spoolID')
    )
    op.create_table('OTDR',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('common_id', sa.Integer(), nullable=False),
    sa.Column('spoolID', sa.String(length=13), nullable=False),
    sa.Column('create_date', sa.DateTime(), nullable=False),
    sa.Column('length', sa.Integer(), nullable=False),
    sa.Column('att1310ise', sa.REAL(), nullable=True),
    sa.Column('att1310ose', sa.REAL(), nullable=True),
    sa.Column('att1550ise', sa.REAL(), nullable=True),
    sa.Column('att1550ose', sa.REAL(), nullable=True),
    sa.Column('att1383ise', sa.REAL(), nullable=True),
    sa.Column('att1383ose', sa.REAL(), nullable=True),
    sa.Column('att1625ise', sa.REAL(), nullable=True),
    sa.Column('att1625ose', sa.REAL(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('spoolID')
    )
    op.create_table('PMD',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('common_id', sa.Integer(), nullable=False),
    sa.Column('spoolID', sa.String(length=13), nullable=False),
    sa.Column('create_date', sa.DateTime(), nullable=False),
    sa.Column('pmd', sa.REAL(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('spoolID')
    )
    op.create_table('chromatic',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('common_id', sa.Integer(), nullable=False),
    sa.Column('spoolID', sa.String(length=13), nullable=False),
    sa.Column('create_date', sa.DateTime(), nullable=False),
    sa.Column('zwl', sa.REAL(), nullable=True),
    sa.Column('slope', sa.REAL(), nullable=True),
    sa.Column('disp1285', sa.REAL(), nullable=True),
    sa.Column('disp1290', sa.REAL(), nullable=True),
    sa.Column('disp1330', sa.REAL(), nullable=True),
    sa.Column('disp1550', sa.REAL(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('spoolID')
    )
    op.create_table('coating',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('common_id', sa.Integer(), nullable=False),
    sa.Column('spoolID', sa.String(length=13), nullable=False),
    sa.Column('create_date', sa.DateTime(), nullable=False),
    sa.Column('coat2Dia', sa.REAL(), nullable=True),
    sa.Column('coat2Ovo', sa.REAL(), nullable=True),
    sa.Column('coat2ECC', sa.REAL(), nullable=True),
    sa.Column('coat1Dia', sa.REAL(), nullable=True),
    sa.Column('coat1Ovo', sa.REAL(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('spoolID')
    )
    op.create_table('common',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('spoolID', sa.String(length=13), nullable=False),
    sa.Column('create_date', sa.DateTime(), nullable=False),
    sa.Column('measure_date', sa.Date(), nullable=False),
    sa.Column('measure_batchNumber', sa.String(length=8), nullable=False),
    sa.Column('info', sa.String(length=23), nullable=False),
    sa.Column('preform', sa.String(length=8), nullable=False),
    sa.Column('ncrCode1', sa.String(length=2), nullable=True),
    sa.Column('ncrCode2', sa.String(length=2), nullable=True),
    sa.Column('ncrCode3', sa.String(length=2), nullable=True),
    sa.Column('resin', sa.String(length=1), nullable=False),
    sa.Column('drawNumber', sa.String(length=2), nullable=False),
    sa.Column('ptNumber', sa.String(length=2), nullable=False),
    sa.Column('com', sa.String(length=2), nullable=False),
    sa.Column('rework', sa.String(length=1), nullable=False),
    sa.Column('productType', sa.String(length=2), nullable=True),
    sa.Column('coat200', sa.String(length=1), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_common_spoolID'), 'common', ['spoolID'], unique=True)
    op.create_table('cutoff',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('common_id', sa.Integer(), nullable=False),
    sa.Column('spoolID', sa.String(length=13), nullable=False),
    sa.Column('create_date', sa.DateTime(), nullable=False),
    sa.Column('fiberCutoffIse', sa.REAL(), nullable=True),
    sa.Column('fiberCutoffOse', sa.REAL(), nullable=True),
    sa.Column('cableCutoff', sa.REAL(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('spoolID')
    )
    op.create_table('draw_number',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('create_date', sa.DateTime(), nullable=False),
    sa.Column('drawNumber', sa.String(length=2), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('drawNumber')
    )
    op.create_table('geometry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('common_id', sa.Integer(), nullable=False),
    sa.Column('spoolID', sa.String(length=13), nullable=False),
    sa.Column('create_date', sa.DateTime(), nullable=False),
    sa.Column('cladDiaIse', sa.REAL(), nullable=True),
    sa.Column('cladDiaOse', sa.REAL(), nullable=True),
    sa.Column('cladOvoIse', sa.REAL(), nullable=True),
    sa.Column('cladOvoOse', sa.REAL(), nullable=True),
    sa.Column('eccIse', sa.REAL(), nullable=True),
    sa.Column('eccOse', sa.REAL(), nullable=True),
    sa.Column('coreOvoIse', sa.REAL(), nullable=True),
    sa.Column('coreOvoOse', sa.REAL(), nullable=True),
    sa.Column('coreDiaIse', sa.REAL(), nullable=True),
    sa.Column('coreDiaOse', sa.REAL(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('spoolID')
    )
    op.create_table('macro_bending',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('common_id', sa.Integer(), nullable=False),
    sa.Column('spoolID', sa.String(length=13), nullable=False),
    sa.Column('create_date', sa.DateTime(), nullable=False),
    sa.Column('R7_1550', sa.REAL(), nullable=True),
    sa.Column('R7_1625', sa.REAL(), nullable=True),
    sa.Column('R10_1550', sa.REAL(), nullable=True),
    sa.Column('R10_1625', sa.REAL(), nullable=True),
    sa.Column('R15_1550', sa.REAL(), nullable=True),
    sa.Column('R15_1625', sa.REAL(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('spoolID')
    )
    op.create_table('ncr_code',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('create_date', sa.DateTime(), nullable=False),
    sa.Column('code', sa.String(length=2), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('packing',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('create_date', sa.DateTime(), nullable=False),
    sa.Column('customerName', sa.String(length=20), nullable=False),
    sa.Column('stdLength', sa.REAL(), nullable=True),
    sa.Column('orderLength', sa.REAL(), nullable=False),
    sa.Column('packedLength', sa.REAL(), nullable=False),
    sa.Column('packedSpoolCount', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('preform',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('create_date', sa.DateTime(), nullable=False),
    sa.Column('preform', sa.String(length=2), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('preform')
    )
    op.create_table('resin',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('create_date', sa.DateTime(), nullable=False),
    sa.Column('resin', sa.String(length=1), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('resin')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('userEmail', sa.String(length=30), nullable=False),
    sa.Column('create_date', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('userEmail')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('resin')
    op.drop_table('preform')
    op.drop_table('packing')
    op.drop_table('ncr_code')
    op.drop_table('macro_bending')
    op.drop_table('geometry')
    op.drop_table('draw_number')
    op.drop_table('cutoff')
    op.drop_index(op.f('ix_common_spoolID'), table_name='common')
    op.drop_table('common')
    op.drop_table('coating')
    op.drop_table('chromatic')
    op.drop_table('PMD')
    op.drop_table('OTDR')
    op.drop_table('MFD')
    # ### end Alembic commands ###
